//! Pedersen commitment constants for Solvasion.
//!
//! C = a·G + r·H where:
//!   G = standard Ristretto255 basepoint
//!   H = HashToRistretto("Solvasion:DefenceCommitment:H:v1")
//!
//! H is derived via hash-to-curve so nobody knows the discrete log
//! relationship between G and H, which is required for the binding
//! property of Pedersen commitments.
//!
//! These bytes were generated by `scripts/derive-generator-h.ts` and
//! cross-verified by `scripts/verify-generator-h.ts`.

use anchor_lang::prelude::*;
use solana_curve25519::ristretto::{PodRistrettoPoint, multiscalar_multiply_ristretto};
use solana_curve25519::scalar::PodScalar;
use crate::errors::SolvasionError;

/// Standard Ristretto255 basepoint (compressed).
pub const GENERATOR_G: PodRistrettoPoint = PodRistrettoPoint([
    0xe2, 0xf2, 0xae, 0x0a, 0x6a, 0xbc, 0x4e, 0x71,
    0xa8, 0x84, 0xa9, 0x61, 0xc5, 0x00, 0x51, 0x5f,
    0x58, 0xe3, 0x0b, 0x6a, 0xa5, 0x82, 0xdd, 0x8d,
    0xb6, 0xa6, 0x59, 0x45, 0xe0, 0x8d, 0x2d, 0x76,
]);

/// H = HashToRistretto("Solvasion:DefenceCommitment:H:v1")
///
/// Derived once via @noble/curves ristretto255_hasher.hashToCurve().
/// Provably independent from G (nobody knows discrete log H/G).
pub const GENERATOR_H: PodRistrettoPoint = PodRistrettoPoint([
    0x94, 0x78, 0x78, 0x1d, 0xe3, 0x45, 0x5f, 0x9c,
    0x86, 0x80, 0x7a, 0xe4, 0x6c, 0x84, 0x33, 0x66,
    0x74, 0x60, 0xd2, 0xb8, 0xef, 0x22, 0x4c, 0x69,
    0x1c, 0x9a, 0x1c, 0xb7, 0x0e, 0x06, 0x8e, 0x3d,
]);

/// Domain separator used to derive H. Kept here for documentation;
/// the on-chain program only needs the precomputed GENERATOR_H bytes.
pub const DOMAIN_SEPARATOR_H: &[u8] = b"Solvasion:DefenceCommitment:H:v1";

/// Identity point (all zeros) — rejected as a sanity check on commitments.
pub const IDENTITY_POINT: [u8; 32] = [0u8; 32];

/// Verify that a stored Pedersen commitment matches the opening (energy_amount, blind).
///
/// Computes C' = energy_amount·G + blind·H and checks C'.0 == stored_commitment.
pub fn verify_commitment(
    stored_commitment: &[u8; 32],
    energy_amount: u32,
    blind: &[u8; 32],
) -> Result<()> {
    // Convert energy amount to 32-byte LE scalar
    let mut energy_bytes = [0u8; 32];
    energy_bytes[..4].copy_from_slice(&energy_amount.to_le_bytes());
    let a_scalar = PodScalar(energy_bytes);
    let r_scalar = PodScalar(*blind);

    let result = multiscalar_multiply_ristretto(
        &[a_scalar, r_scalar],
        &[GENERATOR_G, GENERATOR_H],
    )
    .ok_or(SolvasionError::CurveOpFailed)?;

    require!(
        result.0 == *stored_commitment,
        SolvasionError::InvalidCommitmentOpening
    );

    Ok(())
}
